applicationApiVersion: v1beta1

properties:
  name:
    type: string
    x-google-marketplace:
      type: NAME
  namespace:
    type: string
    x-google-marketplace:
      type: NAMESPACE
  sysdig.serviceAccount.name:
    type: string
    x-google-marketplace:
      type: SERVICE_ACCOUNT
      serviceAccount:
        roles:
        - type: ClusterRole
          rulesType: CUSTOM
          rules:
          - apiGroups:
              - ""
            resources:
              - pods
              - replicationcontrollers
              - services
              - events
              - limitranges
              - namespaces
              - nodes
              - resourcequotas
            verbs:
              - get
              - list
              - watch
          - apiGroups:
              - apps
            resources:
              - daemonsets
              - deployments
              - replicasets
              - statefulsets
            verbs:
              - get
              - list
              - watch
          - apiGroups:
              - autoscaling
            resources:
              - horizontalpodautoscalers
            verbs:
              - get
              - list
              - watch
          - apiGroups:
              - batch
            resources:
              - cronjobs
              - jobs
            verbs:
              - get
              - list
              - watch
          - apiGroups:
              - extensions
            resources:
              - daemonsets
              - deployments
              - ingresses
              - replicasets
            verbs:
              - get
              - list
              - watch
  sysdig.sysdig.accessKey:
    title: Sysdig Access Key
    type: string
  image:
    type: string
    default: $REGISTRY/agent:$TAG
    x-google-marketplace:
      type: IMAGE
      image:
        generatedProperties:
          splitToRegistryRepoTag:
            registry: sysdig.image.registry
            repo: sysdig.image.repository
            tag: sysdig.image.tag
  sysdig.ebpf.enabled:
    title: Enable eBPF support for Sysdig Agent
    type: boolean
    default: false
required:
- name
- namespace
- image
- sysdig.sysdig.accessKey
