applicationApiVersion: v1beta1

properties:
  name:
    type: string
    x-google-marketplace:
      type: NAME
  namespace:
    type: string
    x-google-marketplace:
      type: NAMESPACE
  sysdig.serviceAccount.name:
    title: Sysdig Agent Service Account
    description: Service account to assign to Sysdig Agent DaemonSet
    type: string
    x-google-marketplace:
      type: SERVICE_ACCOUNT
      serviceAccount:
        roles:
        - type: ClusterRole
          rulesType: PREDEFINED
          rulesFromRoleName: cluster-admin
  sysdig.sysdig.accessKey:
    title: Sysdig Access Key
    description: |-
      You can get your Access Key in your Sysdig Platform settings.

      If you need more details, please access to the Sysdig Documentation entry: https://bit.ly/2TNqIRf
    type: string
  image:
    type: string
    default: $REGISTRY/agent:$TAG
    x-google-marketplace:
      type: IMAGE
      image:
        generatedProperties:
          splitToRegistryRepoTag:
            registry: sysdig.image.registry
            repo: sysdig.image.repository
            tag: sysdig.image.tag
  sysdig.ebpf.enabled:
    title: Enable eBPF support for Sysdig Agent
    description: |-
      Mark this checkbox if you are using a Kernel newer than 4.14. The default
      value for newly created clusters is enabled, but if you are using an older
      kernel, please uncheck this checkbox and use the Sysdig Kernel mmodule for
      capturing the system calls.
    type: boolean
    default: true
required:
- name
- namespace
- image
- sysdig.sysdig.accessKey
